import type { Inflection } from '../src/inflection';
import type { Concat } from '../src/utils';

const cases: [
  string,
  [Concat<[Inflection['case'], '-', Inflection['number']]>, string][],
][] = [
  [
    'мо 1a',
    [
      ['nom-sg', ''],
      ['nom-pl', 'ы'],
      ['gen-sg', 'а'],
      ['gen-pl', 'ов'],
      ['dat-sg', 'у'],
      ['dat-pl', 'ам'],
      ['acc-sg', 'а'],
      ['acc-pl', 'ов'],
      ['ins-sg', 'ом'],
      ['ins-pl', 'ами'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ах'],
    ],
  ],
  [
    'м 1a',
    [
      ['nom-sg', ''],
      ['nom-pl', 'ы'],
      ['gen-sg', 'а'],
      ['gen-pl', 'ов'],
      ['dat-sg', 'у'],
      ['dat-pl', 'ам'],
      ['acc-sg', ''],
      ['acc-pl', 'ы'],
      ['ins-sg', 'ом'],
      ['ins-pl', 'ами'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ах'],
    ],
  ],
  [
    'мо 2a',
    [
      ['nom-sg', 'ь'],
      ['nom-pl', 'и'],
      ['gen-sg', 'я'],
      ['gen-pl', 'ей'],
      ['dat-sg', 'ю'],
      ['dat-pl', 'ям'],
      ['acc-sg', 'я'],
      ['acc-pl', 'ей'],
      ['ins-sg', 'ем'],
      ['ins-pl', 'ями'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ях'],
    ],
  ],
  [
    'м 2a',
    [
      ['nom-sg', 'ь'],
      ['nom-pl', 'и'],
      ['gen-sg', 'я'],
      ['gen-pl', 'ей'],
      ['dat-sg', 'ю'],
      ['dat-pl', 'ям'],
      ['acc-sg', 'ь'],
      ['acc-pl', 'и'],
      ['ins-sg', 'ем'],
      ['ins-pl', 'ями'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ях'],
    ],
  ],
  [
    'жо 1a',
    [
      ['nom-sg', 'а'],
      ['nom-pl', 'ы'],
      ['gen-sg', 'ы'],
      ['gen-pl', ''],
      ['dat-sg', 'е'],
      ['dat-pl', 'ам'],
      ['acc-sg', 'у'],
      ['acc-pl', ''],
      ['ins-sg', 'ой'],
      ['ins-pl', 'ами'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ах'],
    ],
  ],
  [
    'ж 1a',
    [
      ['nom-sg', 'а'],
      ['nom-pl', 'ы'],
      ['gen-sg', 'ы'],
      ['gen-pl', ''],
      ['dat-sg', 'е'],
      ['dat-pl', 'ам'],
      ['acc-sg', 'у'],
      ['acc-pl', 'ы'],
      ['ins-sg', 'ой'],
      ['ins-pl', 'ами'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ах'],
    ],
  ],
  [
    'жо 2a',
    [
      ['nom-sg', 'я'],
      ['nom-pl', 'и'],
      ['gen-sg', 'и'],
      ['gen-pl', 'ь'],
      ['dat-sg', 'е'],
      ['dat-pl', 'ям'],
      ['acc-sg', 'ю'],
      ['acc-pl', 'ь'],
      ['ins-sg', 'ей'],
      ['ins-pl', 'ями'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ях'],
    ],
  ],
  [
    'ж 2a',
    [
      ['nom-sg', 'я'],
      ['nom-pl', 'и'],
      ['gen-sg', 'и'],
      ['gen-pl', 'ь'],
      ['dat-sg', 'е'],
      ['dat-pl', 'ям'],
      ['acc-sg', 'ю'],
      ['acc-pl', 'и'],
      ['ins-sg', 'ей'],
      ['ins-pl', 'ями'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ях'],
    ],
  ],
  [
    'со 1a',
    [
      ['nom-sg', 'о'],
      ['nom-pl', 'а'],
      ['gen-sg', 'а'],
      ['gen-pl', ''],
      ['dat-sg', 'у'],
      ['dat-pl', 'ам'],
      ['acc-sg', 'о'],
      ['acc-pl', ''],
      ['ins-sg', 'ом'],
      ['ins-pl', 'ами'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ах'],
    ],
  ],
  [
    'с 1a',
    [
      ['nom-sg', 'о'],
      ['nom-pl', 'а'],
      ['gen-sg', 'а'],
      ['gen-pl', ''],
      ['dat-sg', 'у'],
      ['dat-pl', 'ам'],
      ['acc-sg', 'о'],
      ['acc-pl', 'а'],
      ['ins-sg', 'ом'],
      ['ins-pl', 'ами'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ах'],
    ],
  ],
  [
    'с 2a',
    [
      ['nom-sg', 'е'],
      ['nom-pl', 'я'],
      ['gen-sg', 'я'],
      ['gen-pl', 'ь'],
      ['dat-sg', 'ю'],
      ['dat-pl', 'ям'],
      ['acc-sg', 'е'],
      ['acc-pl', 'я'],
      ['ins-sg', 'ем'],
      ['ins-pl', 'ями'],
      ['prp-sg', 'е'],
      ['prp-pl', 'ях'],
    ],
  ],
];

export default cases;
